### ISSUE TITLE
ignoreFields of ExportResultsCommand in resultcenter is ignored

### ISSUE THREAD

**Issue by oliverkosky** [conterra/mapapps-query-builder#17]
# Reproduction

- Create a query builder query
- Configure resultcenter to ignore some fields for CSV export
- Query features

# Expected

- CSV does not contain ignored fields

# Actual

- CSV still contains all fields of the service

# Note

- We used a configuration that worked for a "normal" selection

**Comment by matthiasstein** [comment]
This problem has the same cause as this one: https://github.com/conterra/mapapps-query-builder/issues/10

If you set _useMemorySelectionStore_ in _QueryBuilderProperties_ to true the Query Builder creates a new _MemorySelectionStore_ to save the results. This allows you to delete results in the Result Center. The newly created store has an id prefixed with _querybuilder__. Consequently, the solution to the problem is:

```
"ExportResultsCommand": {
    "mimetype": "text/csv",
    "filename": "resultcenter.csv",
    "separator": ";",
    "undefinedValue": "",
    "ignoreFields": {
        "querybuilder_stoerungen": [
            "melder"
        ]
    }
}
```
